environment:

    ##########################################################################
    # The following variables describe the currently active toolchain and
    # should not be overridden by the user.
    ##########################################################################

    # The default build (i.e. the system that the build runs on) and host
    # system (i.e. the system where the produced executables run on)
    # definition.
    ARCH:           "$(host-arch)"
    # This is the platform on which the compilation tools are executed.
    AUTOCONF_BUILD: "$(host-autoconf)"
    # This is the platform on which the compiled code will eventually run.
    AUTOCONF_HOST:  "$(host-autoconf)"

    GITHUB_MIRROR:        "https://github.com"
    GITLAB_MIRROR:        "https://gitlab.com"
    PYTHON_MIRROR:        "https://www.python.org/ftp/python"
    DEVELOPER_ARM_MIRROR: "https://developer.arm.com"
    JAVA_MIRROR:          "https://download.java.net"
    SOURCEFORGE_MIRROR:   "https://sourceforge.net"

    # This is for local (user) specific usage. Let this environment variable
    # point to your internal PiPy Mirror storage in order to install pip packages
    # without the usage of external internet access.
    #
    # example:
    #   PYTHON_PYPI_MIRROR:   \\\\MY-NETWORK-DRIVE\\pypi.mirror\\packages\\wheels
    #
    PYTHON_PYPI_MIRROR:   ""

    # This will enable/disable the clang host toolchain if required by the user. If set to
    # "True" some initial tools will be bootstrapped using the native MSVC compiler because
    # they are required to build the clang toolchain.
    ENABLE_X86_64_CLANG_HOST_TOOLCHAIN: "False"

    # Enable/Disable the Microsoft Visual Studio 2019 toolchain (MSBuildTools)
    # Note: The default VS toolchain is v143 (MSBuildTools 2022) independent of this setting
    ENABLE_VS_BUILDTOOLS_2019: "False"
    # Enable/Disable the Microsoft Visual Studio 2026 toolchain (MSBuildTools)
    # Note: The default VS toolchain is v143 (MSBuildTools 2022) independent of this setting
    ENABLE_VS_BUILDTOOLS_2026: "False"

    # This is for local (user) specific usage. Let this environment variable
    # point to your local storage where the vs20xx BuildTools offline bundle is stored.
    #
    # If not set, the (online) layout(s) will be downloaded from the official microsoft mirror.
    # If set, the (offline) zip bundle(s) will be downloaded from a specific secondary mirror.
    #
    # example:
    #   # use secondary mirror from a internal network drive
    #   SCM_VS_OFFLINE_BUNDLE_DIRECTORY:   \\\\MY-NETWORK-DRIVE\\windows
    #
    # example:
    #   # use official files from microsoft mirror (default setting)
    #   SCM_VS_OFFLINE_BUNDLE_DIRECTORY:   ""
    #
    # note:
    #  You can build an offline bundle by executing e.g:
    #
    #                -  'bob dev devel::win10-sdk-bundle'.
    #                -  'bob dev devel::msvc-v142-layout-bundle'.
    #
    #  The result of this package is a zip archive which can be copied to the path configured
    #  in 'SCM_VS_OFFLINE_BUNDLE_DIRECTORY'.
    #  Note: Please take care that the variable 'SCM_VS_OFFLINE_BUNDLE_DIRECTORY' is not set,
    #        so that the microsoft mirror is used as source to create the offline cache.
    SCM_VS_OFFLINE_BUNDLE_DIRECTORY: ""

    # This variable can be used to clear and rebuild the local cache of the
    # Visual Studio Developer Command Prompt. Normally, this variable does not
    # need to be modified. The cache is automatically initialized during the
    # first build of a package.
    #
    # The purpose of the cache is to avoid repeatedly loading environment variables
    # from the vcvarsall.bat file, which can take several seconds. When frequently
    # rebuilding packages that use the MSVC toolchain, this delay can quickly become
    # annoying.
    MSVC_REBUILD_VCVARS_CACHE: "False"

whitelist:
    - "PROCESSOR_ARCHITECTURE"
    #- "PROCESSOR_IDENTIFIER"
    #- "PROCESSOR_LEVEL"
    #- "PROCESSOR_REVISION"

include:
    # optional include for user specific settings.
    # note: This file (user.yaml) is not under version control and shall be placed
    #       in the root directory of the project relative to the default.yaml.
    - user
    # optional include for user specific binary archives.
    # note: This file (archive.yaml) is not added to .gitignore and shall be placed
    #       in the root directory of the project relative to the default.yaml.
    - archive
