environment:

    ##########################################################################
    # The following variables describe the currently active toolchain and
    # should not be overridden by the user.
    ##########################################################################

    # The default build (i.e. the system that the build runs on) and host
    # system (i.e. the system where the produced executables run on)
    # definition.
    ARCH:           "$(host-arch)"
    AUTOCONF_BUILD: "$(host-autoconf)"
    AUTOCONF_HOST:  "$(host-autoconf)"

    GITHUB_MIRROR:        "https://github.com"
    GITLAB_MIRROR:        "https://gitlab.com"
    PYTHON_MIRROR:        "https://www.python.org/ftp/python"
    DEVELOPER_ARM_MIRROR: "https://developer.arm.com"

    # This is for local (user) specific usage. Let this environment variable
    # point to you internal PIPY Mirror storage in order to install pip packages
    # without the usage of external internet access.
    #
    # example:
    #   PYTHON_PYPI_MIRROR:   \\\\MY-NETWORK-DRIVE\\pypi.mirror\\packages\\wheels
    #
    PYTHON_PYPI_MIRROR:   ""

include:
    - user