environment:

    ##########################################################################
    # The following variables describe the currently active toolchain and
    # should not be overridden by the user.
    ##########################################################################

    # The default build (i.e. the system that the build runs on) and host
    # system (i.e. the system where the produced executables run on)
    # definition.
    ARCH:           "$(host-arch)"
    AUTOCONF_BUILD: "$(host-autoconf)"
    AUTOCONF_HOST:  "$(host-autoconf)"

    GITHUB_MIRROR:        "https://github.com"
    GITLAB_MIRROR:        "https://gitlab.com"
    PYTHON_MIRROR:        "https://www.python.org/ftp/python"
    DEVELOPER_ARM_MIRROR: "https://developer.arm.com"
    JAVA_MIRROR:          "https://download.java.net"
    SOURCEFORGE_MIRROR:   "https://sourceforge.net"

    # This is for local (user) specific usage. Let this environment variable
    # point to you internal PIPY Mirror storage in order to install pip packages
    # without the usage of external internet access.
    #
    # example:
    #   PYTHON_PYPI_MIRROR:   \\\\MY-NETWORK-DRIVE\\pypi.mirror\\packages\\wheels
    #
    PYTHON_PYPI_MIRROR:   ""

    # This will enable/disable the finger-printing script of the vs2019 native toolchain.
    # The variable should always set to True but can be changed to False during development
    # to speed up the build execution time because fingerprinting is executed every time a
    # build is triggered.
    ENABLE_NATIVE_TOOLCHAIN_FINGERPRINTING: "True"

    # This will enable/disable the clang host toolchain if required by the user. If set to
    # "True" some initial tools will be bootstrapped using the native MSVC compiler because
    # they are required to build the clang toolchain. After building the clang toolchain, the
    # clang toolchain earns the role of the master host toolchain.
    # If set to "False" the MSVC compiler becomes the master host toolchain.
    USE_CLANG_AS_HOST_TOOLCHAIN: "True"

include:
    # optional include for user specific settings.
    # note: This file (user.yaml) is not under version control and shall be placed
    #       in the root directory of the project relative to the default.yaml.
    - user
    # optional include for user specific binary archives.
    # note: This file (archive.yaml) is not added to .gitignore and shall be placed
    #       in the root directory of the project relative to the default.yaml.
    - archive
